// src/services/token.service.js
// Atomic token generation with mutex to prevent duplicates under concurrent load

const { Mutex } = require('async-mutex');
const { getCounter, setCounter, getTokenByTokenId, createToken } = require('./sheets.service');
const { TOKEN_PREFIX, TOKEN_YEAR, STATUS_ACTIVE } = require('../config/constants');

// Process-level mutex: only one request can run the token-generation critical section at a time
const tokenMutex = new Mutex();

/**
 * Format: SSEC-2026-0001 (4-digit sequence)
 */
function buildTokenId(counter) {
  const padded = String(counter).padStart(4, '0');
  return `${TOKEN_PREFIX}-${TOKEN_YEAR}-${padded}`;
}

/**
 * Atomically generate the next unique token number.
 */
async function generateUniqueTokenId() {
  const release = await tokenMutex.acquire();
  try {
    let attempts = 0;
    while (attempts < 10) {
      const current = await getCounter();
      const next = current + 1;
      const candidate = buildTokenId(next);

      // Verify it doesn't already exist
      const existing = await getTokenByTokenId(candidate);
      if (existing) {
        await setCounter(next);
        attempts++;
        continue;
      }

      await setCounter(next);
      return candidate;
    }
    throw new Error('Failed to generate a unique token after 10 attempts');
  } finally {
    release();
  }
}

/**
 * Student registration flow:
 * 1. Generate unique token atomically
 * 2. Write record to Sheets (S.No auto-generated by sheets.service)
 */
async function registerStudent(data) {
  const tokenId = await generateUniqueTokenId();

  const now = new Date();
  const pad = n => String(n).padStart(2, '0');
  const generatedDate = `${pad(now.getDate())}-${pad(now.getMonth() + 1)}-${now.getFullYear()}`;
  const generatedTime = `${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;

  const studentType = data.studentType || data.hostelOrDayScholar || 'Day Scholar';
  const studentMobile = (data.studentMobile || '').trim();

  const tokenRecord = {
    tokenId,
    studentName: data.studentName.trim(),
    studentType,
    hostelOrDayScholar: studentType,
    parentNumber: (data.parentNumber || '').trim(),
    studentMobile,
    generatedDate,
    generatedTime,
    status: STATUS_ACTIVE,
  };

  const created = await createToken(tokenRecord);
  return { ...tokenRecord, sno: created.sno };
}

module.exports = { generateUniqueTokenId, registerStudent };
