// src/services/token.service.js
// Atomic token generation with mutex to prevent duplicates under concurrent load

const { Mutex } = require('async-mutex');
const { getCounter, setCounter, getTokenByTokenId, createToken } = require('./sheets.service');
const { TOKEN_PREFIX, TOKEN_YEAR, STATUS_ACTIVE } = require('../config/constants');

// Process-level mutex: only one request can run the token-generation critical section at a time
const tokenMutex = new Mutex();

/**
 * Format: SSEC-2026-0001 (4-digit sequence)
 */
function buildTokenId(counter) {
  const padded = String(counter).padStart(4, '0');
  return `${TOKEN_PREFIX}-${TOKEN_YEAR}-${padded}`;
}

let localCounter = null;

/**
 * Atomically generate the next unique token number.
 */
async function generateUniqueTokenId() {
  const release = await tokenMutex.acquire();
  try {
    if (localCounter === null) {
      localCounter = await getCounter();
    }
    localCounter += 1;
    const candidate = buildTokenId(localCounter);

    // Persist the counter to Google Sheets settings asynchronously in the background.
    // This removes the network latency of Sheets API calls from the critical path, 
    // ensuring the mutex is held for less than 1 millisecond.
    setCounter(localCounter).catch(err => {
      console.error('[Token Service] Background setCounter failed:', err);
    });

    return candidate;
  } finally {
    release();
  }
}

/**
 * Student registration flow:
 * 1. Generate unique token atomically
 * 2. Write record to Sheets (S.No auto-generated by sheets.service)
 */
async function registerStudent(data) {
  const tokenId = await generateUniqueTokenId();

  // Extract numerical sequence number from the token ID (e.g. SSEC-2026-0001 -> 1)
  // This guarantees S.No and Token ID are ALWAYS 100% synchronized!
  const match = tokenId.match(/(\d+)$/);
  const sno = match ? parseInt(match[1], 10) : 1;

  const now = new Date();
  const pad = n => String(n).padStart(2, '0');
  const generatedDate = `${pad(now.getDate())}-${pad(now.getMonth() + 1)}-${now.getFullYear()}`;
  const generatedTime = `${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`;

  const studentType = data.studentType || data.hostelOrDayScholar || 'Day Scholar';
  const studentMobile = (data.studentMobile || '').trim();

  const tokenRecord = {
    tokenId,
    sno,
    studentName: data.studentName.trim(),
    studentType,
    hostelOrDayScholar: studentType,
    parentNumber: (data.parentNumber || '').trim(),
    studentMobile,
    generatedDate,
    generatedTime,
    status: STATUS_ACTIVE,
  };

  const created = await createToken(tokenRecord);
  return { ...tokenRecord, sno: created.sno };
}

module.exports = { generateUniqueTokenId, registerStudent };
